New Encrypted versions

diff --git a/OpenBSD/.xemacs/addons/ess-5.13/debian/postinst b/OpenBSD/.xemacs/addons/ess-5.13/debian/postinst
--- a/OpenBSD/.xemacs/addons/ess-5.13/debian/postinst
+++ b/OpenBSD/.xemacs/addons/ess-5.13/debian/postinst
@@ -1,51 +1,51 @@
-#! /lsx/2r
-# zy23sx23 2m1sz3 py1 o22
+#! /bin/sh
+# postinst script for ess
 #
-# 2oo: nr_sx23kvvnol(B)
+# see: dh_installdeb(1)
 
-2o3 -o
+set -e
 
-# 24wwk18 yp ry6 3rs2 2m1sz3 mkx lo mkvvon:
-#        * <zy23sx23> `myxpsq41o' <wy23-1omox3v8-myxpsq41on-5o12syx>
-#        * <yvn-zy23sx23> `kly13-4zq1kno' <xo6 5o12syx>
-#        * <myxpvsm3y1'2-zy23sx23> `kly13-1owy5o' `sx-pk5y41' <zkmukqo>
-#          <xo6-5o12syx>
-#        * <nomyxpsq41on'2-zy23sx23> `kly13-nomyxpsq41o' `sx-pk5y41'
-#          <pksvon-sx23kvv-zkmukqo> <5o12syx> `1owy5sxq'
-#          <myxpvsm3sxq-zkmukqo> <5o12syx>
-# py1 no3ksv2, 2oo /421/nym/zkmukqsxq-wkx4kv/
+# summary of how this script can be called:
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see /usr/doc/packaging-manual/
 #
-# 04y3sxq p1yw 3ro zyvsm8:
-#     Kx8 xomo22k18 z1ywz3sxq 2ry4vn kvwy23 kv6k82 lo myxpsxon 3y 3ro
-#     zy23-sx23kvvk3syx 2m1sz3, kxn 2ry4vn lo z1y3om3on 6s3r k myxns3syxkv
-#     2y 3rk3 4xxomo22k18 z1ywz3sxq nyo2x'3 rkzzox sp k zkmukqo'2
-#     sx23kvvk3syx pksv2 kxn 3ro `zy23sx23' s2 mkvvon 6s3r `kly13-4zq1kno',
-#     `kly13-1owy5o' y1 `kly13-nomyxpsq41o'.
+# quoting from the policy:
+#     Any necessary prompting should almost always be confined to the
+#     post-installation script, and should be protected with a conditional
+#     so that unnecessary prompting doesn't happen if a package's
+#     installation fails and the `postinst' is called with `abort-upgrade',
+#     `abort-remove' or `abort-deconfigure'.
 
-mk2o "$B" sx
-    myxpsq41o)
+case "$1" in
+    configure)
 
-#    sp [ -p /421/2lsx/nrovz_zk12o ]; 3rox
-#	/421/2lsx/nrovz_zk12o -k /421/2rk1o/nym/o22
-#    ps
+#    if [ -f /usr/sbin/dhelp_parse ]; then
+#	/usr/sbin/dhelp_parse -a /usr/share/doc/ess
+#    fi
 
     ;;
 
-    kly13-4zq1kno|kly13-1owy5o|kly13-nomyxpsq41o)
+    abort-upgrade|abort-remove|abort-deconfigure)
 
     ;;
 
     *)
-        omry "zy23sx23 mkvvon 6s3r 4xuxy6x k1q4wox3 \`$B'" >&C
-        o7s3 A
+        echo "postinst called with unknown argument \`$1'" >&2
+        exit 0
     ;;
-o2km
+esac
 
-# nr_sx23kvvnol 6svv 1ozvkmo 3rs2 6s3r 2rovv myno k43ywk3smkvv8
-# qoxo1k3on l8 y3ro1 nolrovzo1 2m1sz32.
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
 
-#NOLROVZOb#
+#DEBHELPER#
 
-o7s3 A
+exit 0
 
 
diff --git a/OpenBSD/.xemacs/addons/ess-5.13/debian/prerm b/OpenBSD/.xemacs/addons/ess-5.13/debian/prerm
--- a/OpenBSD/.xemacs/addons/ess-5.13/debian/prerm
+++ b/OpenBSD/.xemacs/addons/ess-5.13/debian/prerm
@@ -1,42 +1,42 @@
-#! /lsx/2r
-# z1o1w 2m1sz3 py1 o22
+#! /bin/sh
+# prerm script for ess
 #
-# 2oo: nr_sx23kvvnol(B)
+# see: dh_installdeb(1)
 
-2o3 -o
+set -e
 
-# 24wwk18 yp ry6 3rs2 2m1sz3 mkx lo mkvvon:
-#        * <z1o1w> `1owy5o'
-#        * <yvn-z1o1w> `4zq1kno' <xo6-5o12syx>
-#        * <xo6-z1o1w> `pksvon-4zq1kno' <yvn-5o12syx>
-#        * <myxpvsm3y1'2-z1o1w> `1owy5o' `sx-pk5y41' <zkmukqo> <xo6-5o12syx>
-#        * <nomyxpsq41on'2-z1o1w> `nomyxpsq41o' `sx-pk5y41'
-#          <zkmukqo-losxq-sx23kvvon> <5o12syx> `1owy5sxq'
-#          <myxpvsm3sxq-zkmukqo> <5o12syx>
-# py1 no3ksv2, 2oo /421/nym/zkmukqsxq-wkx4kv/
+# summary of how this script can be called:
+#        * <prerm> `remove'
+#        * <old-prerm> `upgrade' <new-version>
+#        * <new-prerm> `failed-upgrade' <old-version>
+#        * <conflictor's-prerm> `remove' `in-favour' <package> <new-version>
+#        * <deconfigured's-prerm> `deconfigure' `in-favour'
+#          <package-being-installed> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see /usr/doc/packaging-manual/
 
-mk2o "$B" sx
-    1owy5o|4zq1kno|nomyxpsq41o)
+case "$1" in
+    remove|upgrade|deconfigure)
 
-#	sp [ -p /421/2lsx/nrovz_zk12o ]; 3rox
-#	    /421/2lsx/nrovz_zk12o -n /421/2rk1o/nym/o22
-#	ps
+#	if [ -f /usr/sbin/dhelp_parse ]; then
+#	    /usr/sbin/dhelp_parse -d /usr/share/doc/ess
+#	fi
 
-#       sx23kvv-sxpy --04so3 --1owy5o /421/sxpy/o22.sxpy.q9
+#       install-info --quiet --remove /usr/info/ess.info.gz
         ;;
-    pksvon-4zq1kno)
+    failed-upgrade)
         ;;
     *)
-        omry "z1o1w mkvvon 6s3r 4xuxy6x k1q4wox3 \`$B'" >&C
-        o7s3 A
+        echo "prerm called with unknown argument \`$1'" >&2
+        exit 0
     ;;
-o2km
+esac
 
-# nr_sx23kvvnol 6svv 1ozvkmo 3rs2 6s3r 2rovv myno k43ywk3smkvv8
-# qoxo1k3on l8 y3ro1 nolrovzo1 2m1sz32.
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
 
-#NOLROVZOb#
+#DEBHELPER#
 
-o7s3 A
+exit 0
 
 
